#Script location:C:\Users\Administrator\AppData\Roaming\mpv
#lua scripts list:autoload/mpv_thumbnail_script_server/osc_tethys/playlistmanager/youtube-search
#conf scripts-opt list:playlistmanager/youtube-search

#Use umpv for one instance

##[video]
profile=high-quality #gpu-hq
vo=gpu-next
gpu-context=d3d11
gpu-api=d3d11 #vulkan
# d3d11-exclusive-fs=yes #stuck
swapchain-depth=1
hwdec=auto-copy #auto-safe
priority=high
video-output-levels=full
video-crop=0x0+0+0

##[option]
# fullscreen=yes
keep-open=yes
# loop-file=inf
ontop=no
keepaspect-window=yes
keepaspect=yes
save-position-on-quit=yes
autocreate-playlist=same
directory-mode=ignore

cache=yes
cache-pause-initial=yes
cache-pause-wait=20
demuxer-max-back-bytes=4GiB
demuxer-max-bytes=4GiB

##[audio]
ao=wasapi
audio-exclusive=yes
# audio-stream-silence
#wasapi-exclusive-buffer=50
audio-file-auto=fuzzy
audio-channels=auto-safe
ad-lavc-downmix=no
audio-buffer=0.1
audio-pitch-correction=yes
audio-display=external-first
# audio-spdif=ac3,dts,eac3,dts-hd,truehd
# af="lavcac3enc=bitrate=640:minch=3"
volume=70
volume-max=130

##[scale]
##[shader]
glsl-shader="B:\mpv\mpv-msvc\shaders\ravu-zoom-ar-r3-rgb.hook"
glsl-shader="B:\mpv\mpv-msvc\shaders\CfL_Prediction.glsl"
#glsl-shader="B:\mpv\mpv-msvc\shaders\ravu-3x-r4.hook"
# glsl-shader="B:\mpv\mpv-msvc\shaders\noise_static_luma.hook"
video-sync=display-resample
interpolation=no
# interpolation-threshold=-1
# scale=ewa_lanczos4sharpest
# cscale=ewa_lanczos
# dscale=ewa_robidoux
# dscale-param1=0
# dscale-param2=0
# cscale=sinc
# cscale-window=blackman
# cscale-radius=3
#tscale=bicubic
tscale=sphinx
tscale-blur=0.6991556596428412
tscale-radius=1.05
tscale-clamp=0.0

##[ui]
#border=no
#audio-display=no
osc=no
force-window=yes
cursor-autohide=100
title-bar=no
osd-bar=yes
osd-font='Trebuchet MS'
osd-font-size=30
# osd-bar-align-y=-1

##[sub]
blend-subtitles=video
sub-auto=fuzzy
sub-fix-timing=no
sub-ass-override=no
demuxer-mkv-subtitle-preroll=yes
subs-with-matching-audio=no
sub-ass-use-video-data=aspect-ratio
sub-font=Carlito
sub-font-size=25
sub-blur=0.1
#sub-pos=0
sub-color="#FFFFFF"
sub-border-size=3.2
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.5
sub-bold=yes
sub-margin-x=100
sub-margin-y=50
sub-gauss=1.0
sub-gray=yes

##[deband]
deband=no
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4

##[misc]
#interpolation-preserve=no
deinterlace=no
dither-depth=auto
dither=fruit
# dither=error-diffusion
# error-diffusion=sierra-lite
force-seekable=yes
hr-seek=yes
hr-seek-framedrop=no
embeddedfonts=yes
#audio-delay=+0.084
autofit=50%
msg-color=yes
msg-module=yes
term-osd-bar=yes

[protocol.http]
#GOD I FUCKING HATE 'MR BE EVIL aka sir JEWGLE de la VON SHEKELTUBE' SO MUCH IS SO UNREAL
hls-bitrate=max
cache=yes
script-opts-append=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=js-runtimes=deno,cookies=~/cookies.txt,yes-playlist=,force-ipv4=,
ytdl-format=bestvideo[height<=?1440][fps<=?60][vcodec^=av0]+bestaudio/best[height<=1080?][fps<=?60][vcodec^=vp9]+bestaudio/best
# bestvideo[height<=?1440][fps<=?60][vcodec^=av0]+bestaudio/bestvideo[height<=?1080][fps<=?60][vcodec^=vp9]+bestaudio/bestvideo+bestaudio/best
# [vcodec~='^(havc|h265)']
force-seekable=no
no-cache-pause

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http
